---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8000}]
  - ["forwarded_port", {guest: 8080, host: 8080}]

  driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    holland:
      enabled: false
    mysql-multi:
      bind_ip: '127.0.0.1'
    cloud:
      public_ipv4: '127.0.0.1'
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'secret'
    mysql:
      server_root_password: 'randompass'
      server_repl_password: 'randompass'
      server_debian_password: 'randompass'
    mystack:
      app_db_user_password: 'randompass'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[mystack::mysql_base]
      - recipe[mystack::default]
  - name: mysql
    run_list:
      - recipe[mystack::mysql_base]
