# Disable requirement of "encoding" headers on files
Encoding:
  Enabled: false

# Increase line length, we're not on VT220s anymore
LineLength:
  Max: 180

# Increase allowed lines in a method.  Short methods are good, but 10 lines
#   is a bit too low.
MethodLength:
  Max: 40

# Favor explicit over implicit code: don't complain of "redundant returns"
RedundantReturn:
  Enabled: false

# Don't complain about if/unless modifiers.  The merit of this is debatable
#   and it will likely require building of over-length lines.
IfUnlessModifier:
  Enabled: false

# Don't complain about older hash rocket hash syntax. This was causing
#   problems when configuring things like 'supports' for resources.
HashSyntax:
  EnforcedStyle: hash_rockets
